import type { FieldDef, NodeSchema } from "@node-playground/types";

export const HTTP_FIELDS: FieldDef[] = [
  {
    key: "method",
    label: "Method",
    type: "enum",
    enum: ["GET", "POST", "PUT", "PATCH", "DELETE"],
    required: true,
    default: "GET",
    group: "inputs",
  },
  {
    key: "url",
    label: "Request URL",
    type: "url",
    required: true,
    placeholder: "https://api.example.com/resource",
    help: "Full URL or use tokens like {{steps.manual1.apiUrl}}",
    group: "inputs",
  },
  {
    key: "queryParams",
    label: "Query Params",
    type: "array",
    widget: "keyValue",
    group: "inputs",
  },
  {
    key: "headers",
    label: "Headers",
    type: "array",
    widget: "keyValueWithType",
    group: "inputs",
  },
  {
    key: "bodyMode",
    label: "Body Mode",
    type: "enum",
    enum: ["none", "json", "form-data", "x-www-form-urlencoded", "raw"],
    default: "none",
    help: "Select body format (like Postman)",
    group: "inputs",
  },
  {
    key: "jsonBody",
    label: "JSON Body",
    type: "string",
    widget: "json-editor",
    help: "Request body as JSON object. Tokens are supported.",
    group: "inputs",
  },
  {
    key: "formDataBody",
    label: "Form Data",
    type: "array",
    widget: "keyValueWithType",
    help: "multipart/form-data - for file uploads and mixed data",
    group: "inputs",
  },
  {
    key: "formUrlEncodedBody",
    label: "Form URL Encoded",
    type: "array",
    widget: "keyValue",
    help: "application/x-www-form-urlencoded - standard form submission",
    group: "inputs",
  },
  {
    key: "rawBody",
    label: "Raw Body",
    type: "string",
    widget: "textarea",
    help: "Raw text body (text/plain). Use for custom formats or plain text.",
    group: "inputs",
  },
  {
    key: "authType",
    label: "Auth Type",
    type: "enum",
    enum: ["none", "bearer", "basic"],
    default: "none",
    group: "auth",
  },
  {
    key: "authBearerToken",
    label: "Bearer Token",
    type: "string",
    help: "Can use tokens like {{steps.manual1.apiKey}}",
    group: "auth",
  },
  {
    key: "authBasicUsername",
    label: "Basic Auth Username",
    type: "string",
    help: "Can use tokens for dynamic username",
    group: "auth",
  },
  {
    key: "authBasicPassword",
    label: "Basic Auth Password",
    type: "string",
    help: "Can use tokens for dynamic password",
    group: "auth",
  },
  {
    key: "timeoutMs",
    label: "Timeout (ms)",
    type: "number",
    default: 30000,
    group: "advanced",
  },
  {
    key: "retryCount",
    label: "Retry Count",
    type: "number",
    default: 0,
    group: "advanced",
  },
  {
    key: "retryBackoff",
    label: "Retry Backoff",
    type: "enum",
    enum: ["none", "exponential"],
    default: "none",
    group: "advanced",
  },
  {
    key: "followRedirects",
    label: "Follow Redirects",
    type: "boolean",
    default: true,
    group: "advanced",
  },
  {
    key: "validationNotes",
    label: "Validation",
    type: "string",
    widget: "textarea",
    help: "Document validation scenarios or notes. Use Fuzz button to auto-fill edge cases.",
    group: "validation",
  },
];

export const HTTP_SCHEMA: NodeSchema = {
  key: "http",
  name: "HTTP Request",
  type: "action",
  inputs: HTTP_FIELDS,
  outputs: [
    { key: "status", type: "number" },
    { key: "statusText", type: "string" },
    { key: "durationMs", type: "number" },
    { key: "size", type: "number" },
    { key: "headers", type: "object" },
    { key: "body", type: "object" },
    { key: "raw", type: "string" },
  ],
};
